### PR TITLE
Implemented Expectation-Maximization algorithm

### PR DESCRIPTION
**Pull request by kouariga**
I just noticed that you wanted to make this module compatible with other packages like Flux and Turing #8.  My implementation follows [Peharz 2016](https://homes.cs.washington.edu/~pedrod/papers/pami17.pdf), and I'm afraid that it doesn't work well with those packages as backpropagation is done explicitly.
Could you please let me know what would be a good approach to implement optimization algorithms in such a way that they are compatible with the packages you mentioned? Now I'm guessing that those packages automatically optimize parameters given model/structure, and explicit implementation of optimization algorithms are unnecessary. I'll look into what these packages actually do.

### CODE REVIEW

**Comment by trappmartin** [comment]
Hi, thanks for starting to work on this. 

Correct, I want to keep this package compatible to `Turing` which means that I'll likely change the type system such that every node is a sub-type of `Distribution` from the `Distributions` package. To keep it compatible to Flux, I would simply try to make sure you can use `Flux.Tracker` or whatever AD is used. But I'm not too strict on this.

Regarding EM and other parameter learning methods. You can implement all of those using some AD interface. The key challenge here is to provide the gradient for `logsumexp` to ensure that the AD is efficient. I tried a bit around, without using a specific implementation of the gradient for `logsumexp`, and discovered that back-prop with AD based computation of those gradients is utterly slow. So I guess this would be the main thing to do. If this is done, one should be able to use EM, gradient based maximum likelihood, maximum conditional likelihood or whatever objective.

**Comment by trappmartin** [comment]
You can also have a look at the naive implementation I did to empirically analyse the optimisation properties of deep SPNs: https://github.com/trappmartin/TPM2019. 

But a better option would be the use of an AD interface such as `Flux.Tracker` or any other package. See: https://github.com/trappmartin/SumProductNetworks.jl/blob/master/examples/parameterOptimization.jl for an example using forward-mode AD (slow).

cc: Robert Peharz (@smatmo)

**Comment by xukai92** [comment]
This is an example of gradient for `logsumexp`: https://github.com/denizyuret/Knet.jl/blob/1d453ddd07f4a1390ebaf0e5f3de85864106b792/src/loss.jl#L229

**Comment by xukai92** [comment]
Oh, it seems that we (TuringLang) also have one: https://github.com/TuringLang/Turing.jl/blob/master/src/core/ad.jl#L163

**Comment by trappmartin** [comment]
Haha, nice. Thanks for looking it up btw!

**Comment by xukai92** [comment]
Did a quick benchmark on simply do `logsumexp(x)` where `x = rand(100)`. The time difference is 9 times lol

**Comment by trappmartin** [comment]
So the KNet one is slower?

**Comment by xukai92** [comment]
No, I mean without defining `logsumexp` as primitive v.s. defining it as primitive (with Tracker). 

The Knet one is exactly same as ours.

**Comment by xukai92** [comment]
Just to confirm back to your words "The key challenge here is to provide the gradient for logsumexp to ensure that the AD is efficient."

**Pull request closed without merging**
